model_list:
  - model_name: bedrock-claude-v3-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0
      aws_region_name: "us-west-2"
      aws_access_key_id: "<replace_with_your_access_key>"
      aws_secret_access_key: "<replace_with_your_secret_key>"
      rpm: 100
  - model_name: bedrock-claude-v3-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0
      aws_region_name: "us-east-1"
      aws_access_key_id: "<replace_with_your_access_key>"
      aws_secret_access_key: "<replace_with_your_secret_key>"
      rpm: 100
  - model_name: bedrock-claude-v3-haiku
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240307-v1:0
      aws_region_name: "us-west-2"
      aws_access_key_id: "<replace_with_your_access_key>"
      aws_secret_access_key: "<replace_with_your_secret_key>"
      rpm: 200
  # - model_name: sagemaker-Yi-1.5-9b
  #   litellm_params:
  #     model: sagemaker/jumpstart-dft-hf-llm-yi-1-5-9b-chat-20241009-070517 # replace with your endpoint
  #     aws_region_name: "us-west-2"
  #     aws_access_key_id: "<replace_with_your_access_key>"
  #     aws_secret_access_key: "<replace_with_your_secret_key>"
router_settings:
  routing_strategy: simple-shuffle
  # routing_strategy: usage-based-routing
  # enable_pre_call_check: true
  num_retries: 3
  timeout: 30
general_settings: 
  master_key: sk-1234
# litellm_settings:
#   success_callback: ["prometheus"]
#   failure_callback: ["prometheus"]
#   fallbacks: [{"bedrock-claude-v3-sonnet": ["bedrock-claude-v3-haiku"]}]
